// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSVeneerIndexJenny
//
// Run 'make gen-cue' from repository root to regenerate.

// Raw generated types from Dashboard kind.
export type {
  Action, ActionType, ActionVariable, ActionVariableType, AnnotationPanelFilter, AnnotationQueryPlacement, AnnotationTarget, DashboardLink, DashboardLinkPlacement, DashboardLinkType, FetchOptions, FieldColor, FieldColorSeriesByMode, GridPos, HttpRequestMethod, InfinityOptions, LibraryPanelRef, RangeMap,
  RegexMap,
  SpecialValueMap, Threshold,
  ThresholdsConfig, ValueMap, ValueMapping, ValueMappingResult, VariableOption, VariableType
} from './raw/dashboard/x/dashboard_types.gen';

// Raw generated enums and default consts from dashboard kind.
export {
  DashboardCursorSync, defaultAction, defaultAnnotationPanelFilter, defaultAnnotationTarget, defaultDashboardCursorSync, defaultDashboardLink,
  defaultFetchOptions, defaultGridPos, defaultInfinityOptions, defaultThresholdsConfig, FieldColorModeId, MappingType,
  SpecialValueMatch, ThresholdsMode, VariableRefresh,
  VariableSort
} from './raw/dashboard/x/dashboard_types.gen';

// The following exported declarations correspond to types in the dashboard@0.0 kind's
// schema with attribute @grafana(TSVeneer="type").
//
// The handwritten file for these type and default veneers is expected to be at
// packages/grafana-schema/src/veneer/dashboard.types.ts.
// This re-export declaration enforces that the handwritten veneer file exists,
// and exports all the symbols in the list.
//
// TODO generate code such that tsc enforces type compatibility between raw and veneer decls
export type {
  AnnotationContainer,
  AnnotationQuery, Dashboard, DataSourceRef,
  DataTransformerConfig, FieldConfig, FieldConfigSource,
  MatcherConfig, Panel, RowPanel, TimeOption,
  TimePickerConfig, VariableModel
} from './veneer/dashboard.types';

// The following exported declarations correspond to types in the dashboard@0.0 kind's
// schema with attribute @grafana(TSVeneer="type").
//
// The handwritten file for these type and default veneers is expected to be at
// packages/grafana-schema/src/veneer/dashboard.types.ts.
// This re-export declaration enforces that the handwritten veneer file exists,
// and exports all the symbols in the list.
//
// TODO generate code such that tsc enforces type compatibility between raw and veneer decls
export {
  defaultAnnotationContainer,
  defaultAnnotationQuery, defaultDashboard, defaultFieldConfig, defaultFieldConfigSource,
  defaultMatcherConfig, defaultPanel, defaultRowPanel, defaultTimePickerConfig, defaultVariableModel,
  VariableHide
} from './veneer/dashboard.types';

