package migrations

const (
	IncidentManagementDescription      = "Incident Management in ITIL-based Service Management products focuses on restoring normal operations quickly by managing incidents through a structured schema. Key elements include Incident ID, Title/Description, Status, Priority, Impact, Urgency, Assigned Group, Resolution Details, and SLAs. It ensures efficient incident resolution, minimizing business disruption and maintaining service quality."
	ChangeManagementDescription        = "Change Management in IT Service Management (ITSM) is a structured approach to handling changes in IT services, infrastructure, or processes to minimize risks and disruptions while ensuring that the changes deliver the desired outcomes."
	ProblemManagementDescription       = "The Problem Management View in Helix ITSM provides a real-time overview of active, pending, and resolved problems, tracking trends, root cause analysis, and SLA compliance. It helps IT teams efficiently manage and resolve problems by visualizing problem status, aging, and related incidents."
	DigitalWorkplaceDescription        = "The Digital Workplace View in Helix ITSM provides a real-time overview of user experiences, including active, pending, and resolved service requests, incidents, and system performance. It tracks trends, user satisfaction, and SLA compliance, helping IT teams efficiently manage and optimize the digital workspace. The view visualizes service health, aging incidents, and user engagement, enabling proactive management of end-user issues and enhancing overall service delivery. By providing actionable insights, it ensures a seamless, productive digital experience for users while reducing service disruptions and improving support efficiency."
	ServiceLevelManagementDescription  = "Service Level Management in ITIL-based Service Management products ensures that agreed-upon service quality levels are defined, monitored, and maintained across IT services. BMC Helix Service Level Management focuses on tracking service performance against SLAs (Service Level Agreements), OLAs (Operational Level Agreements), and UCs (Underpinning Contracts). Key elements include SLA Name, Service Target, Goal Type, Start/End Time, Measurement Criteria, Status, Breach Status, and Related Incidents or Requests. It enables proactive management of service commitments, improves transparency, and supports continuous improvement of service delivery."
	ConfigurationManagementDescription = "BMC Helix CMDB (Configuration Management Database) serves as a centralized repository for storing information about Configuration Items (CIs) and their relationships across the IT environment. It supports ITIL-based Configuration Management by enabling organizations to identify, control, maintain, and verify CIs throughout their lifecycle. Key elements include:CI Identification: Servers, applications, network devices, business services, etc. CI Attributes: Name, type, status, owner, location, version, and custom metadata. Relationships: Dependencies, containment, usage, and connectivity between CIs. Reconciliation & Normalization: Ensures data accuracy from multiple discovery sources. Impact Analysis: Helps understand the effect of changes or incidents on dependent services. Federation: Allows integration with external data sources without full duplication. BMC Helix CMDB ensures data consistency across ITSM processes (like Incident, Change, and Asset Management), supporting better decision-making, compliance, and efficient service delivery."
)
